// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxoufxuysxounwndjzbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4b3VmeHV5c3hvdW53bmRqemJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTc5NDAsImV4cCI6MjA2NTU5Mzk0MH0.ox_I_cd1eA5URcG49mrJAe_jaL-aKWGcljcoNTpznvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);